create table public.memorial_profiles (
  id uuid not null default extensions.uuid_generate_v4 (),
  user_id uuid null,
  order_id uuid null,
  slug character varying(255) null,
  profile_name character varying(200) not null,
  profile_image_url text null,
  banner_image_url text null,
  description text null,
  birth_date date null,
  death_date date null,
  gallery_images jsonb null,
  memorial_video_url text null,
  template_id character varying(50) null,
  is_published boolean null default true,
  edit_count integer null default 0,
  max_edits integer null default 1,
  qr_code_url text null,
  qr_data jsonb null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  published_at timestamp with time zone null,
  favorite_music text null,
  deleted_at timestamp with time zone null,
  visit_count integer null default 0,
  constraint memorial_profiles_pkey primary key (id),
  constraint memorial_profiles_slug_key unique (slug),
  constraint memorial_profiles_order_id_fkey foreign KEY (order_id) references orders (id),
  constraint memorial_profiles_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;